//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class TamilMovy
    {
        public int Mid { get; set; }
        public string MovieName { get; set; }
        

        public Nullable<System.DateTime> DateOfRelease { get; set; }
    }
}
